### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by silence-moon** [caojiezhang/VSR-Transformer#12]
![image](https://user-images.githubusercontent.com/48373941/141067499-efa884f3-396d-469f-bc93-bb388bcdb10e.png)
你好，上图我我在REDS上进行训练，但是这个l_pix看起来特别大，请问这是什么情况？

**Comment by ChenShuwei1001** [comment]
因为loss reduction是sum，不是mean

**Comment by silence-moon** [comment]
那，请问可以把你训练过程的loss图展示一下吗？
