### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by silence-moon** [caojiezhang/VSR-Transformer#13]
当加载您提供的模型vsrTransformer_reds_x4_final.pth进行测试的时候，报了如下的错误：
![image](https://user-images.githubusercontent.com/48373941/141674833-7535e7d5-7bf5-42e7-b112-32e11e7a6196.png)

请问是后来的网络修改了还是？

**Comment by xiongguoyu** [comment]
请问一下你有没有解决这个问题，我也遇到了
