### ISSUE TITLE
The provided spynet_sintel_final-3d2a1287.pth model does not match the network

### ISSUE THREAD

**Issue by HangFang6** [caojiezhang/VSR-Transformer#14]
![image](https://user-images.githubusercontent.com/87681879/141986035-c252bc26-3903-4708-9d79-71b4892e1011.png)
Hello! I have some questions when I test you code.
The error is that provided spynet_sintel_final-3d2a1287.pth model does not match the network.
Can you provide me the true model file? Thanks ！！！
I will be appreciated if you can reply to me as soon as you can. Thanks a lot.

**Comment by H-deep** [comment]
+1

**Comment by HangFang6** [comment]
I have resolved this issue, thanks!

**Comment by sunyclj** [comment]
> I have resolved this issue, thanks!

请问spynet_sintel_final-3d2a1287.pth模型在哪里下载的？

**Comment by HangFang6** [comment]
> 

https://drive.google.com/drive/folders/1ABb8DGBzIjgMW_t84R5nl6AAdahaLpIW?usp=sharing

**Comment by xiongguoyu** [comment]
请问你是怎么解决的，我也遇到了这个问题

**Comment by HangFang6** [comment]
@xiongguoyu https://drive.google.com/drive/folders/1ABb8DGBzIjgMW_t84R5nl6AAdahaLpIW?usp=sharing
If it still doesn't work, please let me know.

**Comment by HangFang6** [comment]
你好，rapo的作者caojiezhang已经重新release了新的spynet.pth，我这里转发作者的链接：https://drive.google.com/drive/folders/1ABb8DGBzIjgMW_t84R5nl6AAdahaLpIW?usp=sharing
________________________________
发件人: xiongguoyu ***@***.***>
发送时间: 2022年4月11日 22:04
收件人: caojiezhang/VSR-Transformer ***@***.***>
抄送: Fang Hang ***@***.***>; State change ***@***.***>
主题: Re: [caojiezhang/VSR-Transformer] The provided spynet_sintel_final-3d2a1287.pth model does not match the network (Issue #14)


请问你是怎么解决的，我也遇到了这个问题

―

**Comment by xiongguoyu** [comment]
非常感谢



---Original---
From: "Fang ***@***.***&gt;
Date: Tue, Oct 11, 2022 17:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [caojiezhang/VSR-Transformer] The providedspynet_sintel_final-3d2a1287.pth model does not match the network (Issue #14)




 你好，rapo的作者caojiezhang已经重新release了新的spynet.pth，我这里转发作者的链接：https://drive.google.com/drive/folders/1ABb8DGBzIjgMW_t84R5nl6AAdahaLpIW?usp=sharing 
 ________________________________ 
 发件人: xiongguoyu ***@***.***&gt; 
 发送时间: 2022年4月11日 22:04 
 收件人: caojiezhang/VSR-Transformer ***@***.***&gt; 
 抄送: Fang Hang ***@***.***&gt;; State change ***@***.***&gt; 
 主题: Re: [caojiezhang/VSR-Transformer] The provided spynet_sintel_final-3d2a1287.pth model does not match the network (Issue #14) 
 
 
 请问你是怎么解决的，我也遇到了这个问题 
 
 ―
